### ISSUE TITLE
ASK：How to solve this?

### ISSUE THREAD

**Issue by ErhuRong** [zcyang/imageqa-san#5]
`when I train the model , the output are as following:`
2016-07-09 16:22:17,087 - INFO - san_att_conv_twolayer - start training
2016-07-09 16:23:25,368 - INFO - data_provision_att_vqa - finished loading data
2016-07-09 16:23:31,685 - INFO - san_att_conv_twolayer - finished building model
Traceback (most recent call last):
  File "san_att_conv_twolayer.py", line 265, in <module>
    train(options)
  File "san_att_conv_twolayer.py", line 164, in train
    = eval(options['optimization'])(shared_params, grad_buf, options)
  File "/home/rongerhu/iQA/imageqa-san-master/src/optimization_weight.py", line 33, in sgd
    name = 'f_param_update')
  File "/home/rongerhu/anaconda2/lib/python2.7/site-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/home/rongerhu/anaconda2/lib/python2.7/site-packages/theano/compile/pfunc.py", line 442, in pfunc
    no_default_updates=no_default_updates)
  File "/home/rongerhu/anaconda2/lib/python2.7/site-packages/theano/compile/pfunc.py", line 207, in rebuild_collect_shared
    raise TypeError(err_msg, err_sug)
TypeError: ('An update must have the same type as the original shared variable (shared_var=conv_unigram_b, shared_var.type=TensorType(float32, vector), update_val=Elemwise{sub,no_inplace}.0, update_val.type=TensorType(float64, vector)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')

**Comment by neermat** [comment]
Hey, I'm getting the same error. Did you find the solution?

**Comment by zcyang** [comment]
THEANO_FLAGS=floatX=float32

**Comment by Adityakunwar** [comment]
In which code do I put this : - THEANO_FLAGS=floatX=float32 ?
