### ISSUE TITLE
ValueError: need more than 7 values to unpack

### ISSUE THREAD

**Issue by SeekPoint** [zcyang/imageqa-san#9]
rzai@rzai00:~/prj/imageqa-san/src$ CUDA_VISIBLE_DEVICES=1 PYTHONPATH=~/prj/imageqa-san/src  python san_att_conv_twolayer.py
Using gpu device 0: GeForce GTX 1080 (CNMeM is disabled, cuDNN 5105)
2016-12-20 11:29:17,803 - INFO - san_att_conv_twolayer - OrderedDict([('data_path', '../data_vqa'), ('feature_file', 'trainval_feat.h5'), ('expt_folder', '../expt'), ('model_name', 'imageqa'), ('train_split', 'trainval1'), ('val_split', 'val2'), ('shuffle', True), ('reverse', False), ('sample_answer', True), ('num_region', 196), ('region_dim', 512), ('n_words', 13746), ('n_output', 1000), ('combined_num_mlp', 1), ('combined_mlp_drop_0', True), ('combined_mlp_act_0', 'linear'), ('sent_drop', False), ('use_tanh', False), ('use_unigram_conv', True), ('use_bigram_conv', True), ('use_trigram_conv', True), ('use_attention_drop', False), ('use_before_attention_drop', False), ('n_emb', 500), ('n_dim', 500), ('n_image_feat', 512), ('n_common_feat', 500), ('num_filter_unigram', 256), ('num_filter_bigram', 512), ('num_filter_trigram', 512), ('n_attention', 512), ('init_type', 'uniform'), ('range', 0.01), ('std', 0.01), ('init_lstm_svd', False), ('optimization', 'sgd'), ('batch_size', 100), ('lr', 0.1), ('w_emb_lr', 80.0), ('momentum', 0.89999998), ('gamma', 1), ('step', 10), ('step_start', 100), ('max_epochs', 50), ('weight_decay', 0.0005), ('decay_rate', 0.99900001), ('drop_ratio', 0.5), ('smooth', 9.9999999e-09), ('grad_clip', 0.1), ('disp_interval', 10), ('eval_interval', 1000), ('save_interval', 500)])
2016-12-20 11:29:17,803 - INFO - san_att_conv_twolayer - start training
2016-12-20 11:37:40,671 - INFO - data_provision_att_vqa - finished loading data
Traceback (most recent call last):
  File "san_att_conv_twolayer.py", line 265, in <module>
    train(options)
  File "san_att_conv_twolayer.py", line 116, in train
    = build_model(shared_params, options)
ValueError: need more than 7 values to unpack
rzai@rzai00:~/prj/imageqa-san/src$

**Comment by zcyang** [comment]
git pull to see the updates

**Comment by SeekPoint** [comment]
fixed
